# -*- coding: utf-8 -*-
"""DawaniSonam_HW2_Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sudiHhSfQcD9fN99UwY8hBIiSZ2WsT9Z

Task 1: For the given data file from our course website (dataPreP.csv): (1) open the file and read it to a Panda’s data frame, (2) identify attributes for which ALL quantitative scales from our lectures are applicable and (3) save it as Quantitative.csv file, then (4) save all remaining attributes in the Others.csv file. How many attributes do you have in each of the saved files?
"""

#Task 1
import pandas as pd 
dataPreP = pd.read_csv("dataPreP.csv") 

Quantitative=dataPreP[['Attr 4','Attr 5','Attr 6','Attr 7','Attr 8','Attr 9','Attr 10','Attr 11','Attr 12',]]
Quantitative.to_csv('Quantitative.csv',index=False)
Others=dataPreP[['Attr 0','Attr 1','Attr 2','Attr 3','Labels',]]
Others.to_csv('Others.csv',index=False)
print('Number of attributes in Quantitative: '+str(len(Quantitative.columns)))
print('Number of attributes in Others: '+str(len(Others.columns)))