# -*- coding: utf-8 -*-
"""DawaniSonam_HW2_Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QSfU8VpTjhcOD0_xlwN67Aa0TXE_8Jnm

Task 4: Read the data from Others.csv file to Panda’s data frame and generate all info that you may need to create Summary Table in Data Quality Report for Categorical Features. What type of attributes do you have in this file? What types of scales are applicable to each of them and why?
"""

#Task 4
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tabulate import tabulate

#Copying Task 1, so that even if Task 1 is not executed before this, Task 2 can have Quantitative.csv
#Task 1
dataPreP = pd.read_csv("dataPreP.csv") 
Quantitative=dataPreP[['Attr 4','Attr 5','Attr 6','Attr 7','Attr 8','Attr 9','Attr 10','Attr 11','Attr 12',]]
Quantitative.to_csv('Quantitative.csv',index=False)
Others=dataPreP[['Attr 0','Attr 1','Attr 2','Attr 3','Labels',]]
Others.to_csv('Others.csv',index=False)
#Task 1 ends


Others=pd.read_csv("Others.csv") 
Others_DQR=Others.describe().T
cols=Others.columns
missPer=Others[cols].isna().sum()/Others.count()
modePer=Others_DQR['freq']/Others_DQR['count']

def Others_2ndmode(Others):
  Others_DQR_wT=Others.describe()
  
  mode2=['a','b','c']
  IC = {'Index Title': ['mode_2nd', 'mode2nd_Freq', 'mode2nd_mode%'],'Attr 0': mode2}
  mode2DF = pd.DataFrame(IC).set_index('Index Title')
  Others_DQR_wT=Others_DQR_wT.append(mode2DF)
  
  Others_2modeDF=pd.DataFrame(Others)
  cols=Others_2modeDF.columns
  for col in cols:
    Others_2modeDF=pd.DataFrame(Others[col])
    Others_2modeDF['freq'] = Others_2modeDF.groupby(col)[col].transform('count')
    Others_2modeDF=Others_2modeDF.drop_duplicates()
    Others_2modeDF=Others_2modeDF.sort_values('freq',ascending=False).reset_index(drop=True)
    Others_DQR_wT[col]['mode_2nd']=Others_2modeDF[col][1]
    Others_DQR_wT[col]['mode2nd_Freq']=Others_2modeDF['freq'][1]
    Others_DQR_wT[col]['mode2nd_mode%']=Others_2modeDF['freq'][1]/1000
  return Others_DQR_wT

Others_DQR=Others_2ndmode(Others)
Others_DQR=Others_DQR.T
Others_DQR['miss%']=missPer
Others_DQR['modePer']=modePer
print('Others_DQR: ')
print(tabulate(Others_DQR, headers='keys', tablefmt='psql'))